packages:
  - 'apps/*'
  - 'packages/*'
  - 'contracts'
  - 'infra'

onlyBuiltDependencies:
  - esbuild
  - prisma
  - '@prisma/engines'

allowBuilds:
  esbuild: true
  prisma: true
  '@prisma/engines': true

minimumReleaseAgeExclude:
  - aws-cdk@2.1139.0
