import json,hashlib,datetime,pathlib
p=pathlib.Path('docs/audit/evidence/qa-09-slo-target-2026-10-03.json.devices.json.observe-3.json');raw=p.read_bytes();r=json.loads(raw)['result'];rows=[x.copy() for x in r['receipts'] if x['device_id']==r['prefix']+'-01' and x['topic_type']=='telemetry' and 10000<=x['seq']<10020];assert len(rows)==20 and all(x['result']=='PROCESSED' for x in rows)
for x in rows:x['deviceTimestampToProcessedMs']=round((datetime.datetime.fromisoformat(x['processed_at'].replace('Z','+00:00'))-datetime.datetime.fromisoformat(x['occurred_at'].replace('Z','+00:00'))).total_seconds()*1000)
sources=[]
for f in ['apps/cloud-api/src/admin/device-console/service.ts','apps/ingestion-worker/src/telemetry/repository.ts','packages/database/prisma/schema.prisma']:
 b=pathlib.Path(f).read_bytes();sources.append({'path':f,'sha256':hashlib.sha256(b).hexdigest()})
o={'scope':'TELEMETRY_PROCESSING_VERSUS_API_VISIBILITY_DIAGNOSTIC','prefix':r['prefix'],'observedReceipt':str(p),'observedReceiptSha256':hashlib.sha256(raw).hexdigest(),'processedSamples':20,'processingSamples':rows,'maxDeviceTimestampToProcessedMs':max(x['deviceTimestampToProcessedMs'] for x in rows),'apiVisibilityProofEquivalent':False,'sourceHypothesis':{'gate':'UNCONFIRMED_TARGET_TIED_BUCKET_ROWS_NOT_CAPTURED','aggregateKey':['deviceId','customerId','siteId','bucketStart'],'consoleWhere':['deviceId'],'consoleOrder':['bucketStart DESC'],'assignmentChangedSiteWithinHour':True,'sameBucketTieBreakerAbsent':True,'nextProbe':'Preserve separate attribution bucket rows and request-correlated console values before cleanup; verify current customer and site semantics'},'sources':sources}
pathlib.Path('docs/audit/evidence/qa-09-telemetry-api-visibility-diagnostic-2026-10-03.json').write_text(json.dumps(o,indent=2)+'\n')
p='docs/audit/QA-09-性能缺口诊断与真实速率SLO复验执行记录-2026-10-03.md';s=pathlib.Path(p).read_text();s=s.replace('在线浏览器24项实际', '[Telemetry只读诊断](evidence/qa-09-telemetry-api-visibility-diagnostic-2026-10-03.json)确认seq10000–10019的20条均PROCESSED，设备时间至处理最大7111ms，API可见8条超时仍保留。源码显示小时行按device/customer/site/hour唯一，console只按device查询、bucketStart降序，缺同小时行选择语义；本轮同小时从无站点改为新站点，存在旧行选择假设。未采集目标双归属行/逐响应值，根因仍待定，不把处理成功升级为API可见PASS。只读窗口内ingestion单分钟Throttles最大21，队列Age最大4秒/Visible最大0，重投SQS MessageId日志检索0命中；均为聚合或缺观测证据，不能证明具体消息消费/限流归因。\n\n在线浏览器24项实际');pathlib.Path(p).write_text(s)
